language: "python"
python: "2.7"
sudo: false
install:
   - pip install pep8
   - pip install -r requirements.txt
   - pip install -r test/requirements.txt
   - pip install coveralls
before_script:
   - cp vmbot/example/config.py ./
   - python tools/init_bot.py
script:
   - pep8 --max-line-length=100 --exclude=jabberbot.py vmbot/
   - pep8 --max-line-length=100 tools/
   - pep8 --max-line-length=100 test/
   - coverage run -m unittest discover
after_success: coveralls
after_script: coverage report
